version: '3'
services:
  marketplace:
    container_name: marketplace
    build: . # Replace with the path to your FastAPI app's directory
    ports:
      - "8058:8058"
    volumes:
      - "./marketplace/data:/app/marketplace/data"
      - "./config.yaml:/app/config.yaml"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/marketplace  # Update the DB name if necessary
    networks:
      - bots_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "~/bots/data:/data/db"  # You can change the data directory as needed
    networks:
      - bots_network

networks:
  bots_network:
    driver: bridge